### ISSUE TITLE
Add a sequence diagram or an overview visual

### ISSUE THREAD

**Issue by Sakurann** [decentralized-identity/credential-manifest#104]
It would be super helpful if we could add a sequence diagram or some kind of visual to illustrate the steps:

1. issuer publishes credential_manifest somewhere (where? wallet has to find it?)
2. wallet sends credential_application
3. issuer returns credential_fulfillment

would be super helpful trying to understand what the spec is trying to do.

**Comment by kimdhamilton** [comment]
What do we think about this?
![swimlanes-1a2372f5b2b65e752f4c2e6f53b38bc9](https://user-images.githubusercontent.com/3945683/180282804-d634d807-cea1-4faa-b0b5-040bb69f4933.png)

**Comment by dtmcg** [comment]
I like the clarifying comments

**Comment by brentzundel** [comment]
@kimdhamilton I like the direction you've recommended and would love to see it as a PR

**Comment by kimdhamilton** [comment]
Will take a stab at it shortly
