### ISSUE TITLE
do we need to indicate version on a particular credential manifest?

### ISSUE THREAD

**Issue by brentzundel** [decentralized-identity/credential-manifest#108]
I create a credential manifest and release it. Then I update the credential manifest. I want a way to indicate that the new credential manifest is a new version of the old one.

**Comment by dtmcg** [comment]
can we have a clarifying example

**Comment by dtmcg** [comment]
some overlap with https://github.com/decentralized-identity/credential-manifest/issues/10

**Comment by decentralgabe** [comment]
I believe this is covered with the identifier property we have for each credential manifest. if the ID is a UUID, is this already solved?

**Comment by brentzundel** [comment]
I agree that the unique ID is sufficient, because the version info can literally be included there.
