### ISSUE TITLE
Credential Application Top-Level Format Property: Unnecessary?

### ISSUE THREAD

**Issue by decentralgabe** [decentralized-identity/credential-manifest#111]
> The credential_application MUST have a format property if the related Credential Manifest specifies a format property. Its value MUST be a subset of the format property in the Credential Manifest that this Credential Submission is related to. This object informs the Issuer which formats the Holder wants to recieve the Claims in.

If the presentation submission has claims, and those claims have format properties in the descriptor map...what is the purpose / utility of having the format properties distinct from the claims themselves?

**Comment by csuwildcat** [comment]
This is about what formats the Issuer should issue them credentials in, vs the Descriptor formats, which describe what formats an Issuer accepts for evaluation.

**Comment by decentralgabe** [comment]
Ah, my misunderstanding.
