### ISSUE TITLE
Credential Response example seems to not fit definition

### ISSUE THREAD

**Issue by djvs** [decentralized-identity/credential-manifest#115]
https://identity.foundation/credential-manifest/#credential-response-2

Noting in particular here, Credential Response is required to either have `fulfillment` or `denial` property, while the example contains neither?  Is the example out of date?

**Comment by decentralgabe** [comment]
Example is out of date, thanks for flagging.

**Comment by djvs** [comment]
It looks like the actual context that `jsonld` attempts to resolve through needs to be updated as well.  Not 100% sure how to access that file via `https://identity.foundation/credential-manifest/response/v1`.   Noticed this stream of issues when the endpoint got renamed suddenly.

**Comment by decentralgabe** [comment]
> Is the verifiableCredential location, from the root of the response object, at `$.credential_response.fulfillment.verifiableCredential`?

no, the VC would be a separate property. so... `$.verifiableCredential` distinct from `$.credential_response.??`
