### ISSUE TITLE
docs: How is the Credential Manifest related to Verifiable Credentials?

### ISSUE THREAD

**Issue by pdxjohnny** [decentralized-identity/credential-manifest#121]
Looking for clarity for myself and others.

**Comment by pdxjohnny** [comment]
Is the Credential Manifest spec intended to hold a structure set of credentials, some of which might be in the [W3C Verifiable Credential](https://www.w3.org/TR/vc-data-model/) format?

**Comment by nklomp** [comment]
No, it is a format for issuers to describe what they need from a subject/holder in order to issue a VC to that subject. It is the cousin of presentation exchange.

Could you tell what isn't clear from the abstract so that it can be improved? 

>For User Agents (e.g. wallets) and other service that wish to engage with Issuers to acquire credentials, there must exist a mechanism for assessing what inputs are required from a Subject to process a request for credential(s) issuance. The Credential Manifest is a common data format for describing the inputs a Subject must provide to an Issuer for subsequent evaluation and issuance of the credential(s) indicated in the Credential Manifest.

> Credential Manifests do not themselves define the contents of the output credential(s), the process the Issuer uses to evaluate the submitted inputs, or the protocol Issuers, Subjects, and their User Agents rely on to negotiate credential issuance.

**Comment by bumblefudge** [comment]
credential issuance : credential manifest :: credential exchange : presentation exchange
?

**Comment by dtmcg** [comment]
@pdxjohnny does https://github.com/decentralized-identity/credential-manifest/issues/125 address your question ?

**Comment by brentzundel** [comment]
Marked as pending close. Will close in 7 days if we get no objection to doing so.
