### ISSUE TITLE
Section on Processing of the Objects

### ISSUE THREAD

**Issue by decentralgabe** [decentralized-identity/credential-manifest#125]
Similar to the [input evaluation](https://identity.foundation/presentation-exchange/#input-evaluation) section in PE, the CM spec should have a set of processing instructions.

This is likely most important for processing a Credential Application, though such instructions could be useful for all three objects the spec defines.

**Comment by bumblefudge** [comment]
nota bene @pdxjohnny -- perhaps adding this section will make high-level explanatory frontmatter that would close #121 more easy to write!

**Comment by kimdhamilton** [comment]
Update Nov 10: we're able to reuse the section from PE, but I noticed that PE processing is missing details about descriptor mapping. I'm working on a proposed fix to maximize reuse between the specs; hoping to have a 1st stab tomorrow
