### ISSUE TITLE
Add a User Story about how CM and PE are related

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/credential-manifest#13]
Holder visits issuer.com
Holder browses credential manifests
Holder requests a credential via PE definition in one such manifest
Holder receives PE + domain and challenge for issuer.com
Hodler submits PE VP to issuer.com

**Comment by llorllale** [comment]
@OR13 

>  Holder requests a credential via PE definition in one such manifest

From my reading of credential-manifest, the Holder should probably send a reduced form of the manifest, something that looks like this:

```json
{
    "issuer": "did:example:123",
    "credential": {
        "name": "Washington State Class A Commercial Driver License",
        "schema": "ipfs:QmPXME1oRtoT627YKaDPDQ3PwA8tdP9rWuAAweLzqSwAWT"
    }
}
```

Maybe `credential.name` should be optional

**Comment by llorllale** [comment]
Or maybe just send a CM's identifier along the idea of #10

**Comment by OR13** [comment]
I think its the latter, at this point... the holder has the domain, challenge, credentials and presentation definitions... the holder crafts the submission.... i don't know that they need to do anything but submit it.... its not a "Credential Manifest" issue... its really a PE issue.

The Presentation Submission can reference the "contract" or "credential manifest" by its identifier.

**Comment by brentzundel** [comment]
Has this been answered? Is there still a need for this? Closing in 7 days if no response.
