### ISSUE TITLE
Should a Credential Application & Response include an Applicant ID?

### ISSUE THREAD

**Issue by decentralgabe** [decentralized-identity/credential-manifest#132]
The Credential Manifest specifies an `issuer` property, showing who created it. A Credential Application does not show who the applicant is outside of the credential(s) they provide that may include their identifier. Similarly, a Credential Response has an `application_id` which shows which application it is responding to, but no mention of who the applicant is. 

I'd like to propose a change to add an `applicant` field to both Credential Applications and Credential Responses to make it explicit the parties involved in the interaction.

**Comment by nitro-neal** [comment]
I will work on this

**Comment by brentzundel** [comment]
addressed with #138, closing
