### ISSUE TITLE
spec_version for v1.0.0 vs URL -- should they be the same?

### ISSUE THREAD

**Issue by kimdhamilton** [decentralized-identity/credential-manifest#148]
In the spec, the value for `spec_version` is "https://identity.foundation/credential-manifest/spec/v1.0.0/". However the v1.0.0 spec is hosted at [https://identity.foundation/credential-manifest/v1.0.0/](https://identity.foundation/credential-manifest/v1.0.0/)

Note the difference is that the first has "spec" in the path:
- https://identity.foundation/credential-manifest/spec/v1.0.0, vs
- https://identity.foundation/credential-manifest/v1.0.0

Is this a typo? If so, which should we update?

**Comment by bumblefudge** [comment]
didcomm and pres-ex use the /spec/ path, so i will PR in a fix to make it consistent (and another PR to the DIF guidelines)
