### ISSUE TITLE
Should CMs be signed by the Issuer's DID?

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/credential-manifest#18]

**Comment by OR13** [comment]
No, they would be retrieved through a channel authorized by the issuer... such as a hub / did comm / TLS from the issuers domain.

**Comment by csuwildcat** [comment]
> No, they would be retrieved through a channel authorized by the issuer... such as a hub / did comm / TLS from the issuers domain.

So it should be impossible to put them in a DID Configuration file so others can consume them via static fetch to validate they are from one of the origin's linked DIDs?

**Comment by OR13** [comment]
I don't know enough about them to say for sure, but my guess is that signing them will almost certainly be redundant to whatever channel security you are relying on to retrieve them.

consider:

https://issuer.example.com/.well-known/did-configuration.json
https://issuer.example.com/credential-manifest/0

note that both of these rely on `https`.

consider:

did:example:123?service=hub&relativeRef=/credential-manifest/0

this relies on whatever security the did controller relies on for hub.

The only case where I would consider the value of signing, is when some intermediary negotiates a credential via a manifest with some 3rd party... and you want to be sure that the intermediary has not tampered with the manifest, and that the 3rd party knows the manifest is for the first party, not the intermediary.... is that a use case?

I thoughtthe goal of hubs was to avoid the need to talk with such intermediaries, and likewise, `did-configuration` relies on the party who cares about DIDs checking the domain link credential themselves.
