### ISSUE TITLE
Path in Display Mapping Objects is an array in the examples

### ISSUE THREAD

**Issue by mnzaki** [decentralized-identity/credential-manifest#24]
About the `path` property, the spec currently reads:
> The object MAY contain a path property, and if present, its value MUST be a JSONPath string expression.

But the examples have arrays of JSONPaths
```json
      {
        "path": ["$.donor", "$.vc.donor"],
        "label": "Organ Donor"
      }
```

Are these meant to be fallbacks of some sort, tried in order?

**Comment by csuwildcat** [comment]
This is an error in the spec text, as it should match the demos and describe that it MUST be an array of JSONPath string expressions. Would you be able to do a PR to correct that language?

**Comment by brentzundel** [comment]
this in now handled in wallet rendering spec and has been fixed there.
