### ISSUE TITLE
security concerns with self-asserted properties of issuer

### ISSUE THREAD

**Issue by dhh1128** [decentralized-identity/credential-manifest#26]
Allowing the prospective issuer of a credential to assert their properties (e.g., thumbnail, description) without any proof feels to me like an antipattern and an invitation to phishing. It is highly insecure, and it reinforces a faulty assumption that it's okay to have individuals and institutions play by different rules as far as authentication is concerned.

I would be happier if we removed the self-asserted properties of the issuer and instead relied upon verifiable credentials to establish the properties of the would-be issuer. If this is a deal-breaker because some people who want to use credential manifests are committed to this insecure behavior, an alternative might be to explain why the self-asserted properties are dangerous and caution people not to use them.

**Comment by dhh1128** [comment]
Tagging @llorllale, who asked me in a Hyperledger call if I could explain why I had some concerns about credential manifests.

**Comment by decentralgabe** [comment]
Could add language warning potential risks of using self-asserted properties.
Having some examples of a Manifest being a VC, or something similar to https://identity.foundation/presentation-exchange/#embed-targets would work.

@dhh1128 are you able to make such a PR?

**Comment by brentzundel** [comment]
Additional spec text to clarify the limits of scope for credential manifest to indicate that helpful wallet software should assess received data (and that a system should exist for verifying issuers, etc) would be helpful.

**Comment by Sakurann** [comment]
if issuer metadata is hosted under .well-known of a domain controlled by the issuer, it becomes within the authority of that domain. whether you trust that domain of the issuer is a separate question - you might ask the user to decide, or have a list of allowed issuer domains. not sure this fits into credential manifest approach, but this is what is done in other specs.

**Comment by dtmcg** [comment]
this is not in scope for credential manifest itself. There is a dedicated work item [Trust Establishment](https://github.com/decentralized-identity/trust-establishment/issues)  to address this 
Will close this issue in next meeting unless there is a strong objection.

**Comment by csuwildcat** [comment]
Because this is a near-existential question that is beyond the capacity of the spec to answer, this is likely something that applications and wallets will help users discern for the foreseeable future.
