### ISSUE TITLE
presentation_definition in cred manifest invites an antipattern

### ISSUE THREAD

**Issue by dhh1128** [decentralized-identity/credential-manifest#28]
The idea of `presentation_definition` as a field is to allow an issuer to say, "We'll issue this credential to you if you prove the thing described in `presentation_definition`. The concern I have with this is that it's a weak and flawed substitute for a real proving protocol -- and by having a field for it in the credential manifest, we may encourage harmful shortcuts.

If the potential issuer wants to condition issuance on proof, there's a robust and easy way to do that: ask the potential holder for proof before issuing, in a separate interaction. Doing so will involve some kind of proving protocol (my natural inclination would be to use DIDComm, but CHAPI could also could be used, as could OIDC+SIOP). All of these describe interaction patterns that include properties such as:

* The ability to negotiate how much is proved, how it is proved, and in what order
* The ability to communicate errors that distinguish between communication problems, crypto problems, versioning problems, and the unacceptability of the furnished proof
* The ability to take turns incrementally accumulating proof/trust (possibly large and rich bodies of proof) until both parties are satisfied

Using a protocol that provides these features is the optimal way to build robust "prove this before we issue to you" guarantees into a workflow. As far as I can tell, the `presentation_definition` field does not contain a challenge or nonce, though I may have missed something. If I am correct, then the data supplied as a response to the credential manifest is subject to replay attacks. Even without that vulnerability, it is hampered from being a robust solution due to the bulleted issues I listed above.

I believe the argument in favor of including this field is that it allows a single round trip to express the entire interaction. However, I believe this is not as desirable as it sounds at first glance, because A) the standards of proof that an issuer will have will very often require a pre-existing relationship that is meaningful and long-running; and B) often payment will be involved. Payment is already a separate protocol. Therefore, trying to lump everything into one protocol is already a non-goal.

I would be happier if `presentation_definition` were removed from the format. Failing that, I think we at least need a section of the spec that discusses what its risks are, and how the problem could be solved more robustly.

**Comment by dhh1128** [comment]
Tagging @llorllale, who asked me in a Hyperledger call if I could explain why I had some concerns about credential manifests.

**Comment by dhh1128** [comment]
@csuwildcat : This makes sense, and I can align with the general philosophy. However, if it is intended that a holder react to the presentation definition by replying with a presentation submission, we have a problem due to replay attack. The issuer has to challenge the holder with something that's specific to the individual interaction (a nonce) before the know that the holder's submission is not a replay -- unless I'm missing something?

**Comment by csuwildcat** [comment]
@dhh1128  the PE spec added a unique ID requirement months ago, so that should take care of replay in general, assuming you used it over an integrity protected protocol (OIDC, DID Comms, etc.). We're all just digging into CM (current spec is just a rough draft) and it doesn't specify anything about being used in requests (it can if folks want it to). It was more intended as a resource, but we can look into the request side of things, if you are interested in that.

**Comment by JaceHensley** [comment]
@dhh1128 Our [WACI spec](https://specs.bloom.co/wallet-credential-interactions) does a lot of what you're talking about too. It defines a protocol using CM and PE as the backbone

**Comment by decentralgabe** [comment]
> As far as I can tell, the presentation_definition field does not contain a challenge or nonce, though I may have missed something. If I am correct, then the data supplied as a response to the credential manifest is subject to replay attacks

There is a unique id per instance of a PD; however this should be covered by the embed target.

**Comment by decentralgabe** [comment]
@dhh1128 per the call today, going to mark this as pending close.

If you still believe in the original issue text we invite you to join the next meeting to discuss on July 14th.

**Comment by brentzundel** [comment]
No response from issue poster, closing.
