### ISSUE TITLE
Document popular design systems

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/credential-manifest#29]
- [Microsoft](https://www.microsoft.com/design/fluent/#/)
- [Google](https://material.io/design)
- [Amazon ](https://abduzeedo.com/amazon-web-services-design-system)
- [Apple](https://developer.apple.com/design/)

**Comment by decentralgabe** [comment]
Is this better suited for the https://identity.foundation/wallet-rendering/ spec?

**Comment by OR13** [comment]
probably, I have not kept up with this work item.

**Comment by decentralgabe** [comment]
Moved to https://github.com/decentralized-identity/wallet-rendering/issues/20
