### ISSUE TITLE
Discovery and exchange/submission protocol missing

### ISSUE THREAD

**Issue by awoie** [decentralized-identity/credential-manifest#3]
There is currently no way to discover claims manifests. Furthermore, it is not specified how to submit the required information from the claim manifest to the issuer. What happens if the claims manifest refers to a verified credential available on a different hub or issuer service. Should we specify that the response is a claims manifest as well?

@csuwildcat are these going to be separate specs?

**Comment by csuwildcat** [comment]
These are known areas we want to cover within this scope, but tried to make
sure we put something out there that's unbound to those functions for the
sake of separating concerns and ensuring an open conversation about
potential solutions.

The goal is very much to specify options for both discovery and submission,
so let's start thinking/proposing ideas for each..

**Comment by JaceHensley** [comment]
Consider using `.well-known/did-configuration.json` 😃

**Comment by decentralgabe** [comment]
Per the call today, this is explicitly out of scope for the spec: it is designed to be protocol agnostic.

Embed targets, which are related, are being covered here https://github.com/decentralized-identity/credential-manifest/issues/26#issuecomment-1177955271
