### ISSUE TITLE
Split up the use cases for the spec

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/credential-manifest#31]
1. As an issuer I want to provide a list of credential that I support for the purpose of holder discovery
2. As a wallet implementer, I want to know how to display a credential to the user
3. As a wallet implementer, I want to know that the display information from an issuer is being used.
4. As a wallet implementer, I want to know that the display information for a credential comes from a 3rd party (EFF, etc.)

**Comment by bumblefudge** [comment]
Any verifier or auditor use cases? One thing the Indy folks talk about all the time is historical query-- can you know what VCs an issuer was offering Nov 18 2019?

**Comment by TomCJones** [comment]
I faced this problem 20 years ago with payments. It seems that the point is, can the.user understand the message. It's almost like the wallet, if it's to be a faithful user agent, must understand the level of sofistication of the user.

**Comment by JaceHensley** [comment]
- As a wallet I want to be able to display UI about a credential before I hold it and after I hold it
    - Before holding credential
        - The intent is to show the user information *about* the VC
        - Might inlcude the type of credential, how long it's valid for, etc
    - After holding credential
        - The intent is to show user information *from* the VC
        - This would include data stored in the VC (email address if it's an email VC)
- As an issuer I want to be able to issue multiple VCs in response to a single presentation_submission
- As a wallet I want to display formatted data values
    - instead of an ISO date string, I'd like to be able to know when a value is a date and how format it
    - Maybe this would be adding a json schema for each "path"?

**Comment by csuwildcat** [comment]
Working on collaborative doc text here: https://hackmd.io/NN1rJe3AT9GY1SenX6f99Q

**Comment by quartzjer** [comment]
I'm just coming up to speed on this effort so pardon the not-fully-informed question.

Is there a reason credential display aspects need to be combined in the same spec with credential issuance request parameters?  The README.md seems to only mention the latter "Format that normalizes the definition of requirements for the issuance of a credential."

Finding consensus on the requirements for requesting a VC from an issuer seems a lot more feasible when it doesn't include styling and display concerns.

The first two use-cases in the hackmd of "Credential Issuance Discovery" and "Credential Requirement Discovery" are already an important and large body of work.

Also important to mention is that there is likely some overlap with the OpenID Foundation SIOP discussions, many of the participants there have a long history with very similar discovery and request patterns.

**Comment by decentralgabe** [comment]
@csuwildcat double nudge

**Comment by decentralgabe** [comment]
Can be an independent document, or considered adding language to the spec.

**Comment by dtmcg** [comment]
@decentralgabe @csuwildcat nudge 2^3

**Comment by csuwildcat** [comment]
On it! Sorry for the delay

**Comment by brentzundel** [comment]
nudge @csuwildcat

**Comment by csuwildcat** [comment]
Closing as completed
