### ISSUE TITLE
Support a way to show information about the Claims being offered before it's transferred to the Holder

### ISSUE THREAD

**Issue by JaceHensley** [decentralized-identity/credential-manifest#44]
There's a use case to display information about the Claim before it's issued and transferred to the Holder. If an issuer only uses `path` within the Output Descriptor Object (ODO) then there would be nothing to display to the user.

Ideas:
- Have a separate property that behaves similarly to the existing "display" property but only allows `text` + `label`
  - IMO this would give the most flexibility
- Add an `example` property to the `ODO` that could be either an inline JSON or URI that resolves to a JSON. This `example` JSON would act as the target for the `path` values within the ODO

**Comment by brentzundel** [comment]
Perhaps the next step should be to add a use case (alongside @csuwildcat  use cases PR) so we can better understand what this is asking for.

**Comment by colbyharrison** [comment]
This is no longer a request. Preemptively closing.
