### ISSUE TITLE
Call the requested inputs a Presentation Definition

### ISSUE THREAD

**Issue by brentzundel** [decentralized-identity/credential-manifest#6]
We discussed on a call the idea to put `input_selection` and `input_descriptors` into an independent object, and seemed to have agreement. 
In the Aries community we have been using the term `Presentation Definition` to describe the holder traits requested by a verifier. I would love for these notions to be aligned and recommend that we call the independent object that contains `input_selection` and `input_descriptors` to be called a `Presentation Definition`
[More information on presentation definitions](https://github.com/hyperledger/indy-hipe/tree/master/text/0119-rich-schemas#presentation-definitions)

**Comment by brentzundel** [comment]
This is what happens when I get too excited about something.
I personally like `proof description` better, but `presentation description` matches the language used in the VC spec and more clearly indicates that they are related, i.e. a presentation description would allow a holder to construct a W3C compliant Verifiable Presentation.

**Comment by csuwildcat** [comment]
I am fine with either one, perhaps we can get some other folks on here who can be opinionated and argue with us? @OR13 @swcurran @talltree @msporny ?

**Comment by OR13** [comment]
I prefer `presentation definition`

**Comment by brentzundel** [comment]
This has been resolved via the creation of the presentation exchange spec which introduces the presentation definition data object.
