### ISSUE TITLE
Add github action to generate html

### ISSUE THREAD

**Issue by kimdhamilton** [decentralized-identity/credential-manifest#62]
Consider adding a github action to generate html from md

**Comment by JaceHensley** [comment]
I'll add this to my PR that removes the html files. I forgot that this repo doesn't do that

**Comment by bumblefudge** [comment]
#63 might do the trick?

**Comment by kimdhamilton** [comment]
We'll use this issue to track general wonkiness.

**Comment by JaceHensley** [comment]
fixed with #64
