### ISSUE TITLE
Passing requested credential type by value in addition to by reference

### ISSUE THREAD

**Issue by Sakurann** [decentralized-identity/credential-manifest#67]
There is a requirement for a protocol that can support credential issuance both 1/ starting with the `credential_manifest` discovery and 2/ without such discovery, where the holder simply tells the issuer in the request which credential type the holder is requesting. The use-case for latter would be when the issuer already has all the information needed to issue a credential to that user for example - we would want to prevent the user from presenting the credentials that the user does not want.

In the request of each flow, in 1/ holder would pass credential manifest id in the `credential_application`, while in 2/ holder would pass the credential type directly. This leads to two separate syntaxes. Would it be possible to have an option in credential manifest to pass requested credential both by reference (`manifest_id`) and by value (credential type)?

Aries seems to be taking a similar approach, choosing to pass credential_manifest with credential type/schema directly instead of credential_applicaiton with manifest_id: https://github.com/hyperledger/aries-rfcs/blob/main/features/0511-dif-cred-manifest-attach/README.md#propose-credential-attachment-format

Apologies if this has been discussed or if this is already possible in the current spec.

**Comment by JaceHensley** [comment]
> The use-case for latter would be when the issuer already has all the information needed to issue a credential to that user
So this use-case is covered already with CM, if the issuer doesn't need to collect information from the user then the `presentation_definition` property on `credential_manifest` can be omitted. Without the CM the user wouldn't really know how what credentials the issue has to offer making it really hard to ask for specific credential types. In this situation how does the user/wallet know how to describe the credential they are trying to claim from the issuer?

**Comment by brentzundel** [comment]
I'm not understanding what you're asking for. Are you wondering if the `credential_application` could be changed so that a `credential_manifest` could be passed by value (in addition to by reference via the `manifest_id`) ?

**Comment by decentralgabe** [comment]
@Sakurann we invite you to join our next call on July 14th, or respond here with more information.

**Comment by Sakurann** [comment]
I am ok closing this. Thanks for discussing!

[OpenID for Verifiable Credential Issuance Spec](https://openid.bitbucket.io/connect/openid-4-verifiable-credential-issuance-1_0.html) ended up defining [Credential Metadata Object](https://openid.bitbucket.io/connect/openid-4-verifiable-credential-issuance-1_0.html#section-11.2.1).
