### ISSUE TITLE
Should the CM include a property indicating what issuance protocols the Issuer supports?

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/credential-manifest#7]
Do we want to include a property the issuer can use to indicate what credential issuance protocols it supports?

**Comment by brentzundel** [comment]
I think this could be valuable, but I wonder how that would be done. For example, how does an issuer indicate that it supports "Aries did-comms, version 1.2, with anoncreds 2.0 signatures"
Or did I just answer my own question?
I also wonder if having the issuer DID is sufficient, at least at first. Or maybe the holder can contact the issuer (maybe using some standard `cred-manifest-inquiry` message format) and inquire directly?

**Comment by llorllale** [comment]
The credential manifest should at the very least indicate the formats the issuer supports (jwts, jsonld, etc).

**Comment by brentzundel** [comment]
this is already done

**Comment by brentzundel** [comment]
re-opening, because I was wrong

**Comment by decentralgabe** [comment]
Related to https://github.com/decentralized-identity/credential-manifest/issues/26#issuecomment-1177955271

**Comment by brentzundel** [comment]
I agree with @decentralgabe

**Comment by brentzundel** [comment]
Based on discussion in credential manifest call, we are closing this.
