### ISSUE TITLE
Confusion with Credential Application definition

### ISSUE THREAD

**Issue by DRK3** [decentralized-identity/credential-manifest#73]
Hi everyone,

There's something I'm finding confusing in the [Credential Application](https://identity.foundation/credential-manifest/#credential-application) section.

It says:

> The Credential Application object MUST contain a credential_application property.

and...

> The Credential Application object MUST contain a presentation_submission property IF the related Credential Manifest contains a presentation_definition.

... and here's the example from the spec:

```
{
  "credential_application": {
    "id": "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d",
    "manifest_id": "WA-DL-CLASS-A",
    "format": {
      "ldp_vc": {
        "proof_type": [
          "JsonWebSignature2020",
          "EcdsaSecp256k1Signature2019"
        ]
      }
    }
  },
  "presentation_submission": {
    "id": "a30e3b91-fb77-4d22-95fa-871689c322e2",
    "definition_id": "32f54163-7166-48f1-93d8-ff217bdb0653",
    "descriptor_map": [
      {
        "id": "input_1",
        "format": "jwt_vc",
        "path": "$.verifiableCredential[0]"
      },
      {
        "id": "input_2",
        "format": "ldp_vc",
        "path": "$.verifiableCredential[1]"
      },
      {
        "id": "input_3",
        "format": "ldp_vc",
        "path": "$.verifiableCredential[2]"
      }
    ]
  }
}
```

It sounds like a Credential Application contains a `credential_application` and (optionally) also a `presentation_submission`.

Does this mean that a Credential Application object, when embedded in another object, would look like this, with effectively a nested "credential_application" layer?

```
{
  "credential_application": {
    "credential_application": {
      "id": "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d",
      "manifest_id": "WA-DL-CLASS-A",
      "format": {
        "ldp_vc": {
          "proof_type": [
            "JsonWebSignature2020",
            "EcdsaSecp256k1Signature2019"
          ]
        }
      }
    },
    "presentation_submission": {
      "id": "a30e3b91-fb77-4d22-95fa-871689c322e2",
      "definition_id": "32f54163-7166-48f1-93d8-ff217bdb0653",
      "descriptor_map": [
        {
          "id": "input_1",
          "format": "jwt_vc",
          "path": "$.verifiableCredential[0]"
        },
        {
          "id": "input_2",
          "format": "ldp_vc",
          "path": "$.verifiableCredential[1]"
        },
        {
          "id": "input_3",
          "format": "ldp_vc",
          "path": "$.verifiableCredential[2]"
        }
      ]
    }
  }
}
```

I noticed that the examples for the Credential Manifest and Credential Fulfillment objects have that extra outer layer, I guess because they also specify how they're supposed to be embedded in a parent object, however Credential Application doesn't specify this. I just assumed it should be `credential_application`... but that creates a weird sort of duplicate nesting, so I'm not exactly sure what's intended.

Thanks!

**Comment by DRK3** [comment]
@JaceHensley Thanks so much for the clarification. I'll think about naming... I'm having a hard time coming up with a better name myself, but I'll let you know if I do.

**Comment by brentzundel** [comment]
I believe this issue has been addressed. It will be closed in 7 days if there is no opposition.

**Comment by DRK3** [comment]
Left one comment on https://github.com/decentralized-identity/credential-manifest/pull/102#issuecomment-1191978259
