### ISSUE TITLE
Typo of CALIM instead of CLAIM

### ISSUE THREAD

**Issue by xtrycatchx** [decentralized-identity/credential-manifest#76]
minor typo of `CALIM` instead of `CLAIM` at https://github.com/decentralized-identity/credential-manifest/blob/1fc76252922a53efa9ebacdaccfc4cb639aa2781/spec/spec.md#general-composition

**Comment by bumblefudge** [comment]
thanks!

**Comment by decentralgabe** [comment]
this has been fixed
