### ISSUE TITLE
Rename Credential Manifest to something that actually fits the defintion

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/credential-manifest#8]
The Credential Manifest isn't really a manifest, and literally every human on earth who ever hears the term is thrown into a state of almost permanent confusion, thus I think we should rename it. Given This resource/JSON doc describes the necessary inputs to be considered by an issuer for issuance of a credential, it is more like a Credential Application Form. I would be fine calling it that, given it is very self-descriptive, but it does sound rather lame. Let the bikeshedding begin.

**Comment by erickuhn19** [comment]
Credential Issuance

**Comment by rceleste125** [comment]
It seems that this could be used for other use cases besides just Issuance.  It's really about expressing an Access Policy to a service.  That service could be a credential issuance service, a lookup service, or any other service that wants to use claims as a means of access.  So maybe "Access Policy" is enough of a name?

**Comment by erickuhn19** [comment]
Isn't the purpose of using this spec to receive something in return, the VC? If you always receive a VC for completing the requirements in this spec, it feels like it's an issuance spec. Access policy would be when a verifier asks to validate a VC which is governed under the Presentation Exchange spec.

**Comment by csuwildcat** [comment]
Ideas:

- Credential Requisition
- Credential Codex

**Comment by mnzaki** [comment]
How about simply "Credential Offer"? And as an added point the field `credential` itself feels more fitting of the `CredentialManifest` type. So it would look something like this in typescript:
```ts
interface CredentialOffer {
  locale?: string
  issuer: IssuerManifest
  credential: CredentialManifest
  presentation_definition?: PresentationDefinition
}
```

**Comment by rceleste125** [comment]
Has the Credential Manifest been replaced by the DIF Presentation Exchange spec?


Best Regards,

Bob Celeste
Founder

I'd love to connect. Here's my calendar link<https://calendly.com/rceleste> to make finding time easy.

[cid:image001.png@01D6F337.062DE430]<http://www.linkedin.com/in/bob-celeste-c4scs>    [cid:image002.png@01D6F337.062DE430] <https://www.youtube.com/channel/UC-MyaB-DNBqM4lurvgWiMdg>



[CSCSNew Center logo w_tagline - SMALLER - 08_30_2016]



Center for Supply Chain Studies
125 North Lincoln Avenue, Ste 200, Newtown, PA 18940
T 215.584.7374  |  M 609.947.2720
E rceleste@C4SCS.org<mailto:rceleste@C4SCS.org>  |  www.C4SCS.org<http://www.c4scs.org/>

**Comment by brentzundel** [comment]
closing as no op if no response in 7 days.
