### ISSUE TITLE
Ensure decoded credential samples are clear

### ISSUE THREAD

**Issue by kimdhamilton** [decentralized-identity/credential-manifest#80]
Note to self: sometimes we mix decoded forms of credentials and it's unclear to implementors. Ensure we clean up

**Comment by dtmcg** [comment]
@kimdhamilton  @bumblefudge nudge

**Comment by bumblefudge** [comment]
i'll do an editorial pass and check for this

**Comment by bumblefudge** [comment]
Seems already covered by the `comment` field inserted at the top of every `verifiableCredential` object of examples
