### ISSUE TITLE
referenced specs should be versioned

### ISSUE THREAD

**Issue by brentzundel** [decentralized-identity/credential-manifest#83]
presentation definition and wallet rendering spec references should be to published versions, not just latest

**Comment by bumblefudge** [comment]
I will update this as soon as PE v2 is cut

**Comment by brentzundel** [comment]
We also need as ratified version of Wallet Rendering to point to, yes?

**Comment by decentralgabe** [comment]
Two options:

1. Release a v1 of wallet rendering ASAP. A v1 can be fast-followed by a v1.1 and so on as the specification becomes more mature.
2. Remove wallet rendering references from the spec. There are a lot, pretty much all of CM: https://identity.foundation/credential-manifest/#credential-manifest---schema

My recommendation is we push for a version for wallet rendering as soon as possible. It's the least headache and allows us flexibility to move forward quickly.
