### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by bumblefudge** [decentralized-identity/credential-manifest#84]
Re-PR the typos fixed in #68 PR (rest of PR superceded on today's call)

**Comment by colbyharrison** [comment]
Additional typo https://identity.foundation/credential-manifest/#credential-application 
First paragraph: "outpus" -> "outputs"

**Comment by dtmcg** [comment]
@bumblefudge what's the action item here?

**Comment by bumblefudge** [comment]
oops those typos from #68 were overtaken by events.  Colby's typo fixed by a one-char PR below.
