### ISSUE TITLE
ODOs as object or URI

### ISSUE THREAD

**Issue by JaceHensley** [decentralized-identity/credential-manifest#89]

**Comment by JaceHensley** [comment]
Notes from 5/5/22 WG call
- Caching: Use standard HTTP headers to control cache
  - when the IRI is an http URL
  - callout that a wallet may or may not cache or cache for ever
- Use an IRI instead of a URI

**Comment by colbyharrison** [comment]
Discussion summary from today. 

Agreed to add to clarification to the spec that OutputDescriptorObject.id can be a uri.

Bloom will write up some documentation about how they use it.
