### ISSUE TITLE
Credential Fulfillment should reference a Credential Application

### ISSUE THREAD

**Issue by decentralgabe** [decentralized-identity/credential-manifest#96]
1. An issuer publishes a Credential Manifest
2. A want-to-be holder submits a Credential Application against the Manifest
3. The issuer fulfills the application, submitting a Credential Fulfillment to the soon-to-be holder

If this flow is a correct understanding of the specification, I note a gap between (2) and (3) where the Credential Fulfillment object does not have the ability to reference a Credential Application. I expect that each object is uniquely identified, and further:
- Credential Applications reference a Credential Manifest by ID
- Credential Fulfillments reference both Credential Applications and Credential Manifests by ID

The ID linkage is missing!

**Comment by decentralgabe** [comment]
cc: @JaceHensley @csuwildcat

**Comment by JaceHensley** [comment]
You're right!

**Comment by decentralgabe** [comment]
https://github.com/decentralized-identity/credential-manifest/pull/97
